mysite/myapp/urls.py
from django.urls import path
from myapp.views import index, index_items

app_name ="myapp"

urlpatterns = [
    path('', index),
    path('<int:my_id>/', index_items, name="detail")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls', namespace="myapp"),)
]

mysite/myapp/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

# Create your views here.

def index(request):
    items = Product.objects.all()
    context = {
        "items": items
    }
    return render(request, "myapp/index.html", context)

def index_items(request,my_id):
    item = Product.objects.get(id=my_id)
    context = {
        "item": item
    }
    return render(request, 'myapp/detail.html', context)

mysite/myapp/templates/myapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Details</h2>
    <h1>{{item.id}}</h1>
    <h1>{{item.name}}</h1>
</body>
</html>

mysite/myapp/templates/myapp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}"> 
    <title>Document</title>
  </head>
  <body class="bg-sky-400">
    <h1>This is simple</h1>
    <h2>
      {% for item in items %}
        <a style="text-decoration: none;" href="{% url 'myapp:detail' item.id %}">ID: {{ item.id }} | {{ item }} | {{ item.price }} | {{ item.description }} <br /></a>
      {% endfor %}
    </h2>
  </body>
</html>